#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Net-AMQP
Version  : 0.06
Release  : 23
URL      : https://cpan.metacpan.org/authors/id/C/CH/CHIPS/Net-AMQP-0.06.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CH/CHIPS/Net-AMQP-0.06.tar.gz
Summary  : 'Advanced Message Queue Protocol (de)serialization and representation'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-2.0
Requires: perl(Data::Dumper)
Requires: perl(File::Path)
Requires: perl(File::Spec)
Requires: perl(Scalar::Util)
Requires: perl(XML::LibXML)
BuildRequires : buildreq-cpan
BuildRequires : perl(Class::Accessor)
BuildRequires : perl(Class::Data::Inheritable)
BuildRequires : perl(Test::Deep)
BuildRequires : perl(XML::LibXML)
BuildRequires : perl(XML::SAX::Exception)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Net::AMQP - Advanced Message Queue Protocol (de)serialization and
representation

%prep
%setup -q -n Net-AMQP-0.06
cd %{_builddir}/Net-AMQP-0.06

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Net-AMQP
cp %{_builddir}/Net-AMQP-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Net-AMQP/f235ba4160673bcb7c9d58c2f09dbc7fc0efadea || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
